var
    DIR_BASE = '/base',
    DIR_SECURE_LIB = '/sys/lib',
    LIB_BODY = DIR_BASE + '/Body',
    LIB_COMMAND = DIR_BASE + '/Command',
    LIB_CONTAINER = DIR_BASE + '/Container',
    LIB_CREATOR = DIR_BASE + '/Creator',
    LIB_INTERACTIVE = DIR_BASE + '/Interactive',
    LIB_LIVING = DIR_BASE + '/Living',
    OBJ_LOGIN = DIR_SECURE_LIB + '/Login',
    LIB_MONSTER = DIR_BASE + '/Monster',
    LIB_NPC = DIR_BASE + + '/NPC',
    LIB_OBJECT = DIR_BASE + '/GameObject',
    LIB_PLAYER = DIR_BASE + '/Player',
    LIB_ROOM = DIR_BASE + '/Room',
    LIB_VERB = DIR_BASE + '/Verb',
    LIB_WEAPON = DIR_BASE + '/Weapon';
